config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :users, only: [:new,:show,:edit,:create,:update,:destroy] do
      collection do
        post 'login'
        get 'login_form'
        post 'logout'
      end
    end
    resources :tags, only: [:index,:show,:create] do
      get 'post', to: 'posts#index'
    end
    resources :posts do
      collection do
        resource :comment, only: [:create,:destroy]
        resource :favorite, only: [:create,:destroy]
      end
    end
    resources :notifications, only: [:index,:destroy]
    root 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :post_id,presence: true
    validates :comment,presence: true
    validates :user_id,presence: true

    def post_comment
        return Post.find_by(id: self.post_id)
    end

    def user_comment
        return User.find_by(id: self.user_id)
    end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    validates :post_id,presence:true
    validates :user_id,presence:true

    def post_favorite
        return Post.find_by(id: self.post_id)
    end

    def user_favorite
        return User.find_by(id: self.user_id)
    end
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content,presence:true
    validates :user_id,presence:true
    validates :tag_id,presence:true
    
    mount_uploader :image, ImagesUploader
    def user_post
        return User.find_by(id: self.user_id)
    end

    def tag_post
        return Tag.find_by(id: self.tag_id)
    end

    def comment_post
        return Comment.where(post_id: self.id)
    end

    def favorite_post
        return Favorite.where(post_id: self.id)
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name,presence: true,uniqueness: true
    validates :caption,presence: true

    def posts_tag
        return Post.where(tag_id: self.id)
    end
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence:true
    validates :email, presence:true, uniqueness: true
    has_secure_password

    mount_uploader :image_name, ImagesUploader
    def posts_user
        return Post.where(user_id: self.id)
    end

    def comments_user
        return Comment.where(user_id: self.id)
    end

    def favorites_user
        return Favorite.where(user_id: self.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    before_action :newtag

    def set_current_user
        @current_user = User.find_by(id: session[:user_id])
    end

    def newtag
        @tagnew = Tag.new
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:id])
        @comment = Comment.new(comment_params)
        @comment.user_id = @current_user.id
        @comment.save

    end

    def destroy
        @comment = Comment.find_by(id: params[:id],post_id: params[:post_id])
        @comment.destroy
    end

    private
    def comment_params
        params.require(:comment).permit(:)
        
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

    def create
        @post = Post.find(params[:id])
        @favorite = Favorite.new(favorite_params)
        @favorite.save
    end

    def destroy
        @favorite = Favorite.find_by(post_id: params[:post_id,user_id: @current_user.id])
        @favorite.destroy
    end

    private
    def favorite_params
        params.require(:favorite).permit(:user_id,:post_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

    def top
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = @current_user.posts_user
    end

    def show
        @post = Post.find(params[:id])
        @tag = @post.tag_post
        @comment = Comment.new
    end

    def edit
        @post = Post.find(params[:id])
    end
    
    def create
        @postnew = Post.new(post_params)
        @postnew.save
        redirect_back(fallback_location: root_path)
    end

    def update
        @post = Post.find(params[:id])
        @post.update(post_params)
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_back(fallback_location: root_path)
    end

    private 
    def post_params
        params.require(:post).permit(:tag_id,:user_id,:content,:image)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    
    def index
        @tags = Tag.all
    end
    
    def show
        @tag = Tag.find(params[:id])
        @posts = @tag.posts_tag
        @postnew = Post.new

    end

    def create
        @tagnew = Tag.new(tag_params)
        @tagnew.save
        flash[:notice] = "タグが作成されました"
        redirect_to tag_path(@tagnew) 
    end

    private
    
    def tag_params
        params.require(:tag).permit(:name,:caption)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end

    def login
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to tags_path
        else
            @error_message = "メールアドレスまたはパスワードが間違っています"
            render("users/login_form")
        end
    end

    def login_form

    end

    def show
        @posts = @current_user.posts_user
        @comments = @current_user.comments_user
        @favorite = @current_user.favorites_user
    end

    def edit

    end

    def update
        @current_user.update(user_params)
        redirect_to user_path(@current_user.id)
    end
    
    def create
        @user = User.new(new_user_params)
        if @user.save
            session[:user_id] =@user.id
            redirect_to tags_path
        else 
            render("users/new")
        end

    end

    def destroy
    end

    def logout
        session[:user_id] = nil
        redirect_to root_path
    end

    private
    def new_user_params
        params.permit(:name, :email, :password)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/show.html.slim
.row
    .col-lg-2.col-md-2
    .col-lg-8.col-md-8.col-sm-12.col-xs-12
        .tag-box
            =link_to tag_path(@tag) do
                p.tag-name
                    = @tag.name
                p.tag-caption
                    = @tag.caption
        .post-show-box
            = l @post.created_at
            p = @post.content

        .post-show-comment
    .col-lg-2.col-md-2

app/views/tags/index.html.slim
.row
    .col-lg-2.col-xl-2
    .col-lg-8.col-xl-8.col-sm-12.col-md-12.col-12
        - @tags.each do |tag|
            .tag-box
                =link_to tag_path(tag) do
                    p.tag-name
                        = "##{tag.name}"
                    p.tag-caption
                        = tag.caption
    .col-lg-2.col-xl-2



        

app/views/tags/show.html.slim
.row
    .col-lg-2.col-md-2
    .col-lg-8.col-md-8.col-sm-12.col-xs-12
        .tag-show-box
            p.tag-title = @tag.name
            p.tag-caption = @tag.caption
            .post-box
                - @posts.each do |post|
                    .post-box
                    =link_to post_path(post) do
                        p.post-create =  l post.created_at
                        p.post-content = post.content
                        = link_to("削除",post_path(post),method: :delete)
            .post-form-new
            = form_for(@postnew) do |f|
                = f.text_area :content
                br
                = f.file_field :image
                = f.hidden_field :tag_id, :value => @tag.id
                = f.hidden_field :user_id, :value => @current_user.id 
                br
                = f.submit '投稿' 
    .col-lg-2.col-md-2

app/views/users/login_form.html.slim
.row style="background-color:white;"
    .col-lg-2.col-xl-2
    .col-lg-8.col-xl-8.col-sm-12.col-md-12.col-12
        - if @error_message
            .form_error
                = @error_message
        h3 style="margin-left:43%;border-bottom:1px solid black;display:inline-block"Sign-in
        .sign_up_form style="padding-top:2%; padding-left:38%; padding-right:38%;"
            =form_tag(login_users_path) do
                h4 Mail
                input name = "email"
                h4 style="margin-top:3%"Password
                input name = "password"
                br
                input.btn.btn-default type = "submit" value = "Sign-in" style="margin-top:15%;"
    .col-lg-2.col-xl-2

app/views/users/new.html.slim
.row style="background-color:white;"
    .col-lg-2.col-md-2
    .col-lg-8.col-md-8.col-sm-12.col-xs-12
        - @user.errors.full_messages.each do |msg|
            .error
                = msg
        h3 style="margin-left:43%;border-bottom:1px solid black;display:inline-block"Sign-up 
        .sign_up_form style="padding-top:2%; padding-left:37%"
            =form_tag(users_path) do
                h4 Name
                input name = "name"
                h4 style="margin-top:3%;" Mail
                input name = "email"
                h4 style="margin-top:3%;"Password
                input type = "password" name = "password"
                br
                input.btn.btn-default type = "submit" value = "Sign-up" style="margin-top:5%;"

app/views/users/show.html.slim
.row
    .col-lg-2.col-md-2
    .col-lg-8.col-md-8.col-sm-12.col-xs-12
        .user-show-image
            - if @current_user.image_name?
                = image_tag @current_user.image_name.url
            - else
                = image_tag "/assets/no_image.jpg", :size => '150x150'
        .user-show-name.user-profile
            p =@current_user.name
        .user-show-post.user-profile
            = link_to("Post",posts_path)
        .user-show-comment.user-profile
            p Comment
        .user-show-favorit.user-profile
            p Favorite
        .user-show-edit.user-profile
            = link_to("Edit",edit_user_path(@current_user.id))
        .user-show-notification.user-profile
            = link_to("Notification",notifications_path)
    .col-lg-2.col-md-2